### ISSUE TITLE
Define method context from a custom contract

### ISSUE THREAD

**Issue by TobiaszCudnik** [disnet/contracts.coffee#31]
Define method context (this) from a custom contract. Below ways i've tried to use, but none worked.

``` coffeescript
TCustomContract = ? { a: Num }
foo :: (@{ TCustomContract }) -> Any
foo :: (@TCustomContract) -> Any
foo = ->
```

**Comment by disnet** [comment]
Added grammar support so this should work now. It's failing on node at the moment but it works in Firefox. Might be an old V8 bug.

**Comment by disnet** [comment]
Ah! Definitely a V8 bug, I ran into it before: https://github.com/disnet/contracts.coffee/blob/master/test/contracts.coffee#L125

Hopefully node 0.7 fixes that. Will test that out when I get a chance.

**Comment by TobiaszCudnik** [comment]
Thanks for the grammar, but indeed it's still broken on node 0.7.5 (ERROR: illegal access).
